### ISSUE TITLE
What languages for Quran translation that should manipulate into Dataset 

### ISSUE THREAD

**Issue by langsari** [langsari/quran-dataset#1]
What MOST uses the languages for ASIAN people?
What MOST uses the languages of Quran translation?

**Comment by langsari** [comment]
english
malayu - arabic
malayu - latin
malaysia language
Chinese - Mandarin
laos
Cambodia
Japanese
thai
indonesia
indian - Hindi
Indian -Urdu
Philipino
Tagalog
Vietnamese
Taiwan - Mandarin
Spanish

**Comment by HossniSama** [comment]
What MOST uses the languages for ASIAN people?
1.Chinese – 1 billion speakers in Asia
2.English – 300 million speakers in Asia
3.Russian – 260 million speakers in Asia
4.Indonesian – 240 million speakers in Asia
5.Arabic – 230 million speakers in Asia
6.Bengali or Bangla – 230 million speakers in Asia
7.Japanese – 120 million speakers in Asia
8.Punjabi – 100 million speakers in Asia
9.Filipino – 93 million speakers in Asia
10.Hindi - 550 million speakers in Asia
11.Korean - 80 million speakers in Asia
12.Vietnamese - 80 million speakers in Asia
13.Telugu - 79 million speakers in Asia
14.Tamil - 73 million speakers in Asia
15.Urdu - 62 million speakers in Asia
16.Bahasa Melayu - 30 million speakers in Asia
17.Lao - 7 million speakers in Asia
18.Khmer - 14 million speakers in Asia
19.Thai - 60 million speakers in Asia
20.Uzbek - 25 million speakers in Asia
What MOST uses the languages of Quran translation?
For I fond the most languages are Arabic to English. Because most of the world can speak and understand English and the word use it is easy to understand.
